<a href="https://colab.research.google.com/github/leitoraincomum/pos-mql/blob/aula-1/Quest1e2_plmql2025_1_aula_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aula 1 - Métodos quantitativos aplicados a logística**

In [ ]:
# Carregando uma biblioteca
import pandas as pd

In [ ]:
#importar um arquivo
from google.colab import files
uploaded = files.upload()

Saving Base de dados a limpar.xlsx to Base de dados a limpar.xlsx

In [ ]:
# transformando o arquivo em conjunto de dados
import io
df = pd.read_excel(io.BytesIO(uploaded['Base de dados a limpar.xlsx']))

In [ ]:
df

,Entrega,Qtd itens,Valor_pedido,cliente,Cidade,Avaliação,Km_percorrida,volumes transportados,índice_ociosidade
0,1.0,306.0,808.470112,1.0,Suzano,regular,74.0,16.0,37.0
1,2.0,144.0,1315.979182,1.0,Suzano,ruim,76.0,7.0,46.0
2,3.0,252.0,714.194519,1.0,Suzano,regular,87.0,11.0,42.0
3,4.0,144.0,1140.879524,1.0,Suzano,regular,85.0,6.0,50.0
4,5.0,54.0,819.787553,1.0,Suzano,bom,51.0,3.0,53.0
...,...,...,...,...,...,...,...,...,...
199,197.0,576.0,1708.362533,5.0,Suzano,bom,60.0,34.0,22.0
200,198.0,432.0,1170.593907,4.0,Itaquaquecetuba,ruim,94.0,27.0,26.0
201,199.0,234.0,651.553261,5.0,Suzano,ruim,75.0,14.0,38.0
202,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,201.0,126.0,659.096393,3.0,Poá,excelente,81.0,6.0,47.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Entrega                202 non-null    float64
 1   Qtd itens              201 non-null    float64
 2   Valor_pedido           201 non-null    float64
 3   cliente                201 non-null    float64
 4   Cidade                 201 non-null    object
 5   Avaliação              201 non-null    object
 6   Km_percorrida          199 non-null    float64
 7   volumes transportados  199 non-null    float64
 8   índice_ociosidade      197 non-null    float64
dtypes: float64(7), object(2)
memory usage: 14.5+ KB

In [ ]:
# contar valores ausentes
pd.isna(df).sum()

Entrega                  2
Qtd itens                3
Valor_pedido             3
cliente                  3
Cidade                   3
Avaliação                3
Km_percorrida            5
volumes transportados    5
índice_ociosidade        7
dtype: int64

In [ ]:
# Identificando observações vazias pela variável mais relevante
pd.isnull(df['Entrega']).sum()

np.int64(2)

In [ ]:
# Removendo as observações vazias
df = df.dropna(how='all')

In [ ]:
df

,Entrega,Qtd itens,Valor_pedido,cliente,Cidade,Avaliação,Km_percorrida,volumes transportados,índice_ociosidade
0,1.0,306.0,808.470112,1.0,Suzano,regular,74.0,16.0,37.0
1,2.0,144.0,1315.979182,1.0,Suzano,ruim,76.0,7.0,46.0
2,3.0,252.0,714.194519,1.0,Suzano,regular,87.0,11.0,42.0
3,4.0,144.0,1140.879524,1.0,Suzano,regular,85.0,6.0,50.0
4,5.0,54.0,819.787553,1.0,Suzano,bom,51.0,3.0,53.0
...,...,...,...,...,...,...,...,...,...
199,197.0,576.0,1708.362533,5.0,Suzano,bom,60.0,34.0,22.0
200,198.0,432.0,1170.593907,4.0,Itaquaquecetuba,ruim,94.0,27.0,26.0
201,199.0,234.0,651.553261,5.0,Suzano,ruim,75.0,14.0,38.0
202,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,201.0,126.0,659.096393,3.0,Poá,excelente,81.0,6.0,47.0

In [ ]:
# contar valores ausentes
pd.isna(df).sum()

Entrega                  0
Qtd itens                1
Valor_pedido             1
cliente                  1
Cidade                   1
Avaliação                1
Km_percorrida            3
volumes transportados    3
índice_ociosidade        5
dtype: int64

In [ ]:
# Retirar observações com valor ausente na variável Cliente
df = df.dropna(subset=['cliente'])

In [ ]:
# Contar valores ausentes
pd.isna(df).sum()

Entrega                  0
Qtd itens                0
Valor_pedido             0
cliente                  0
Cidade                   0
Avaliação                0
Km_percorrida            2
volumes transportados    2
índice_ociosidade        4
dtype: int64

In [ ]:
df

,Entrega,Qtd itens,Valor_pedido,cliente,Cidade,Avaliação,Km_percorrida,volumes transportados,índice_ociosidade
0,1.0,306.0,808.470112,1.0,Suzano,regular,74.0,16.0,37.0
1,2.0,144.0,1315.979182,1.0,Suzano,ruim,76.0,7.0,46.0
2,3.0,252.0,714.194519,1.0,Suzano,regular,87.0,11.0,42.0
3,4.0,144.0,1140.879524,1.0,Suzano,regular,85.0,6.0,50.0
4,5.0,54.0,819.787553,1.0,Suzano,bom,51.0,3.0,53.0
...,...,...,...,...,...,...,...,...,...
198,196.0,630.0,929.234568,8.0,Itaquaquecetuba,excelente,58.0,40.0,16.0
199,197.0,576.0,1708.362533,5.0,Suzano,bom,60.0,34.0,22.0
200,198.0,432.0,1170.593907,4.0,Itaquaquecetuba,ruim,94.0,27.0,26.0
201,199.0,234.0,651.553261,5.0,Suzano,ruim,75.0,14.0,38.0
203,201.0,126.0,659.096393,3.0,Poá,excelente,81.0,6.0,47.0

In [ ]:
df["Km_percorrida"]=df["Km_percorrida"].fillna(df["Km_percorrida"].mean())

<ipython-input-14-feaa3727dd4e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Km_percorrida"]=df["Km_percorrida"].fillna(df["Km_percorrida"].mean())

In [ ]:
# Contar valores ausentes
pd.isna(df).sum()

Entrega                  0
Qtd itens                0
Valor_pedido             0
cliente                  0
Cidade                   0
Avaliação                0
Km_percorrida            0
volumes transportados    2
índice_ociosidade        4
dtype: int64

In [ ]:
# Identificar observações duplicadas
df.duplicated().sum()

np.int64(1)

In [ ]:
# excluindo observações duplicadas
df = df.drop_duplicates()

In [ ]:
df

,Entrega,Qtd itens,Valor_pedido,cliente,Cidade,Avaliação,Km_percorrida,volumes transportados,índice_ociosidade
0,1.0,306.0,808.470112,1.0,Suzano,regular,74.0,16.0,37.0
1,2.0,144.0,1315.979182,1.0,Suzano,ruim,76.0,7.0,46.0
2,3.0,252.0,714.194519,1.0,Suzano,regular,87.0,11.0,42.0
3,4.0,144.0,1140.879524,1.0,Suzano,regular,85.0,6.0,50.0
4,5.0,54.0,819.787553,1.0,Suzano,bom,51.0,3.0,53.0
...,...,...,...,...,...,...,...,...,...
198,196.0,630.0,929.234568,8.0,Itaquaquecetuba,excelente,58.0,40.0,16.0
199,197.0,576.0,1708.362533,5.0,Suzano,bom,60.0,34.0,22.0
200,198.0,432.0,1170.593907,4.0,Itaquaquecetuba,ruim,94.0,27.0,26.0
201,199.0,234.0,651.553261,5.0,Suzano,ruim,75.0,14.0,38.0
203,201.0,126.0,659.096393,3.0,Poá,excelente,81.0,6.0,47.0

In [ ]:
# Verificar se há erros de grafia em variáveis categóricas
df["Cidade"].unique()

array(['Suzano', 'Mogi das Cruzes', 'Suzno', 'Itaquaquecetuba', 'Poá',
       'Mogi dasCruzes', 'Poa'], dtype=object)

In [ ]:
# Corrigir a grafia de Mogi das Cruzes
df["Cidade"]=df["Cidade"].replace({"Mogi dasCruzes":'Mogi das Cruzes'},regex=True)

<ipython-input-20-69d1cdf2e698>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cidade"]=df["Cidade"].replace({"Mogi dasCruzes":'Mogi das Cruzes'},regex=True)

In [ ]:
# Verificar se há erros de grafia em variáveis categóricas
df["Cidade"].unique()

array(['Suzano', 'Mogi das Cruzes', 'Suzno', 'Itaquaquecetuba', 'Poá',
       'Poa'], dtype=object)

In [ ]:
# Corrigir a grafia de Suzno e Poa (multiplas correções)
df["Cidade"]=df["Cidade"].replace({"Suzno":'Suzano',"Poa":'Poá'},regex=True)

<ipython-input-23-19cca0b9a08d>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Cidade"]=df["Cidade"].replace({"Suzno":'Suzano',"Poa":'Poá'},regex=True)

In [ ]:
# Verificar se há erros de grafia em variáveis categóricas
df["Cidade"].unique()

array(['Suzano', 'Mogi das Cruzes', 'Itaquaquecetuba', 'Poá'],
      dtype=object)

In [ ]:
# Exportando o arquivo tratado
from google.colab import files
df.to_excel("df.xlsx")
files.download("df.xlsx")

**Questionário 1**

In [ ]:
# Carregando uma biblioteca
import pandas as pd

In [ ]:
#importar um arquivo
from google.colab import files
uploaded = files.upload()

Saving base2.xlsx to base2.xlsx

In [ ]:
# transformando o arquivo em conjunto de dados
import io
df = pd.read_excel(io.BytesIO(uploaded['base2.xlsx']))

In [ ]:
df

,CUST_NAME,Gender_Code,ADDRESS1,CITY,STATE,COUNTRY_CODE,POSTAL_CODE,POSTAL_CODE_PLUS4,ADDRESS2,EMAIL_ADDRESS,...,Cleaning Products,Condiments,Frozen Foods,Kitchen Items,Meat,Office Supplies,Personal Care,Pet Supplies,Sea Food,Spices
0,Allen Perl,Mr.,4707 Hillcrest Lane,Abeto,PG,IT,6040,0.0,NaN,Allen.M.Perl@spambob.com,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Allen Perl,Mr.,4707 Hillcrest Lane,Abeto,PG,IT,6040,0.0,NaN,Allen.M.Perl@spambob.com,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Allen Perl,Mr.,4707 Hillcrest Lane,Abeto,PG,IT,6040,0.0,NaN,Allen.M.Perl@spambob.com,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Allen Perl,Mr.,4707 Hillcrest Lane,Abeto,PG,IT,6040,0.0,NaN,Allen.M.Perl@spambob.com,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Allen Perl,Mr.,4707 Hillcrest Lane,Abeto,PG,IT,6040,0.0,NaN,Allen.M.Perl@spambob.com,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,Rebecca Uresti,Mrs.,4333 Morningview Lane,Birmingham,AL,US,35203,0.0,NaN,Rebecca.C.Uresti@trashymail.com,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
200,Emma Perez,Mrs.,1199 Lightning Point Drive,Black Hawk,SD,US,57718,0.0,NaN,Emma.V.Perez@spambob.com,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
201,Reynaldo Myers,Mr.,3923 Black Stallion Road,Blaxland East,NSW,AU,2774,0.0,NaN,Reynaldo.J.Myers@pookmail.com,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
202,Reynaldo Myers,Mr.,3923 Black Stallion Road,Blaxland East,NSW,AU,2774,0.0,NaN,Reynaldo.J.Myers@pookmail.com,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
203,Jennifer Becker,Mrs.,4374 Lindale Avenue,Bloomington,IL,US,61701,0.0,NaN,Jennifer.D.Becker@spambob.com,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

In [ ]:
# exibe a quantidade de linhas e colunas do dataset
df.shape

(204, 62)

In [ ]:
# exibindo valores da coluna POSTAL_CODE
df.POSTAL_CODE

0       6040
1       6040
2       6040
3       6040
4       6040
       ...
199    35203
200    57718
201     2774
202     2774
203    61701
Name: POSTAL_CODE, Length: 204, dtype: object

In [ ]:
#exibindo valores da coluna FREIGHT_CHARGES
df.FREIGHT_CHARGES

0      29.79
1      17.87
2      31.88
3      18.45
4      23.12
       ...
199     7.45
200     5.66
201     6.15
202    18.24
203    10.45
Name: FREIGHT_CHARGES, Length: 204, dtype: float64

In [ ]:
#exibindo valores da coluna ORDER_TYPE
df.ORDER_TYPE

0      MediumValue
1      MediumValue
2         LowValue
3         LowValue
4         LowValue
          ...
199       LowValue
200       LowValue
201       LowValue
202       LowValue
203      HighValue
Name: ORDER_TYPE, Length: 204, dtype: object

**Questionário 2**

In [ ]:
# Identificar observações duplicadas
df.duplicated().sum()

np.int64(9)

In [ ]:
# excluindo observações duplicadas
df = df.drop_duplicates()

In [ ]:
# exibe a quantidade de linhas e colunas do dataset
df.shape

(195, 62)

In [ ]:
# Contar valores ausentes na coluna STATE
pd.isna(df.STATE).sum()

np.int64(37)

In [ ]:
# Contar valores ausentes na coluna AGE
pd.isna(df.AGE).sum()

np.int64(25)

In [ ]:
#Contar valores ausentes
pd.isna(df).sum()

CUST_NAME           1
Gender_Code         1
ADDRESS1            1
CITY                1
STATE              37
                   ..
Office Supplies     1
Personal Care       1
Pet Supplies        1
Sea Food            1
Spices              1
Length: 62, dtype: int64

In [ ]:
# contando a quantidade de anotações vazias
df.isnull().all(axis=1).sum()

np.int64(1)

In [ ]:
# listando os nomes das colunas
df.columns

Index(['CUST_NAME', 'Gender_Code', 'ADDRESS1', 'CITY', 'STATE', 'COUNTRY_CODE',
       'POSTAL_CODE', 'POSTAL_CODE_PLUS4', 'ADDRESS2', 'EMAIL_ADDRESS',
       'PHONE_NUMBER', 'CREDITCARD_TYPE', 'LOCALITY', 'SALESMAN_ID',
       'NATIONALITY', 'NATIONAL_ID', 'CREDITCARD_NUMBER', 'DRIVER_LICENSE',
       'CUST_ID', 'ORDER_ID', 'ORDER_DATE', 'ORDER_TIME', 'FREIGHT_CHARGES',
       'ORDER_SALESMAN', 'ORDER_POSTED_DATE', 'ORDER_SHIP_DATE', 'AGE',
       'ORDER_VALUE', 'T_TYPE', 'PURCHASE_TOUCHPOINT', 'PURCHASE_STATUS',
       'ORDER_TYPE', 'GENERATION', 'Baby Food', 'Diapers', 'Formula', 'Lotion',
       'Baby wash', 'Wipes', 'Fresh Fruits', 'Fresh Vegetables', 'Beer',
       'Wine', 'Club Soda', 'Sports Drink', 'Chips', 'Popcorn', 'Oatmeal',
       'Medicines', 'Canned Foods', 'Cigarettes', 'Cheese',
       'Cleaning Products', 'Condiments', 'Frozen Foods', 'Kitchen Items',
       'Meat', 'Office Supplies', 'Personal Care', 'Pet Supplies', 'Sea Food',
       'Spices'],
      dtype='object')

In [ ]:
# Identificando qual bandeira de cartão contém erro de grafia
df["CREDITCARD_TYPE"].unique()

array(['Master Card', 'VISA', 'Discover', 'American Express',
       'American Expres', 'Diners Club', 'jcb', nan], dtype=object)

In [ ]:
# Renomeando o cartão
df["CREDITCARD_TYPE"] = df["CREDITCARD_TYPE"].replace({"American Expresss":'American Express'},regex=True)

<ipython-input-46-f740d9f40108>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["CREDITCARD_TYPE"] = df["CREDITCARD_TYPE"].replace({"American Expresss":'American Express'},regex=True)

In [ ]:
df["CREDITCARD_TYPE"].unique()

array(['Master Card', 'VISA', 'Discover', 'American Express',
       'Diners Club', 'jcb', nan], dtype=object)

In [ ]:
# Removendo as observações vazias
df = df.dropna(how='all')

In [ ]:
pd.isnull(df).sum()

CUST_NAME           0
Gender_Code         0
ADDRESS1            0
CITY                0
STATE              36
                   ..
Office Supplies     0
Personal Care       0
Pet Supplies        0
Sea Food            0
Spices              0
Length: 62, dtype: int64

In [ ]:
# Exportando o arquivo tratado
from google.colab import files
df.to_excel("baselimpa.xlsx")
files.download("baselimpa.xlsx")